site_name: ProyectoFinal

theme:
  name: flatly
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings:
     default_handler: python
     handlers:
       python:
         paths:[proyecto]
       site_dir: docs
  - search


nav:
  - Main: index.md
  - Planteamiento: planteamiento.md
  - Reference: reference.md
  
